want_go_cities = ['Tokyo','Osaga','Kyoto','Spporo','HongKong']
print(want_go_cities)
print(sorted(want_go_cities))
print(want_go_cities)
print(sorted(want_go_cities,reverse = True))
print(want_go_cities)
want_go_cities.reverse()
print(want_go_cities)
want_go_cities.reverse()
print(want_go_cities)
want_go_cities.sort()
print(want_go_cities)
want_go_cities.sort(reverse = True)
print(want_go_cities)